language: rust

install:
  - sh ./.travis.install.deps.sh

script:
  - make
  - make test -j4
  - make install DESTDIR=${PWD}/destdir

env:
  matrix:
    - BITS=32
    - BITS=64

os:
  - linux
  - osx
